#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanNongSan.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNONGSAN")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insert_Admin(_Admin instance);
    partial void Update_Admin(_Admin instance);
    partial void Delete_Admin(_Admin instance);
    partial void InsertCT_hoa_don(CT_hoa_don instance);
    partial void UpdateCT_hoa_don(CT_hoa_don instance);
    partial void DeleteCT_hoa_don(CT_hoa_don instance);
    partial void InsertKhach_hang(Khach_hang instance);
    partial void UpdateKhach_hang(Khach_hang instance);
    partial void DeleteKhach_hang(Khach_hang instance);
    partial void InsertHoa_don(Hoa_don instance);
    partial void UpdateHoa_don(Hoa_don instance);
    partial void DeleteHoa_don(Hoa_don instance);
    partial void InsertLoai_nong_san(Loai_nong_san instance);
    partial void UpdateLoai_nong_san(Loai_nong_san instance);
    partial void DeleteLoai_nong_san(Loai_nong_san instance);
    partial void InsertSan_pham(San_pham instance);
    partial void UpdateSan_pham(San_pham instance);
    partial void DeleteSan_pham(San_pham instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLNONGSANConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<_Admin> _Admins
		{
			get
			{
				return this.GetTable<_Admin>();
			}
		}
		
		public System.Data.Linq.Table<CT_hoa_don> CT_hoa_dons
		{
			get
			{
				return this.GetTable<CT_hoa_don>();
			}
		}
		
		public System.Data.Linq.Table<Khach_hang> Khach_hangs
		{
			get
			{
				return this.GetTable<Khach_hang>();
			}
		}
		
		public System.Data.Linq.Table<Hoa_don> Hoa_dons
		{
			get
			{
				return this.GetTable<Hoa_don>();
			}
		}
		
		public System.Data.Linq.Table<Loai_nong_san> Loai_nong_sans
		{
			get
			{
				return this.GetTable<Loai_nong_san>();
			}
		}
		
		public System.Data.Linq.Table<San_pham> San_phams
		{
			get
			{
				return this.GetTable<San_pham>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_Admin]")]
	public partial class _Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_admin;
		
		private string _ten_dang_nhap;
		
		private string _mat_khau;
		
		private string _email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_adminChanging(int value);
    partial void Onma_adminChanged();
    partial void Onten_dang_nhapChanging(string value);
    partial void Onten_dang_nhapChanged();
    partial void Onmat_khauChanging(string value);
    partial void Onmat_khauChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public _Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_admin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_admin
		{
			get
			{
				return this._ma_admin;
			}
			set
			{
				if ((this._ma_admin != value))
				{
					this.Onma_adminChanging(value);
					this.SendPropertyChanging();
					this._ma_admin = value;
					this.SendPropertyChanged("ma_admin");
					this.Onma_adminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_dang_nhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_dang_nhap
		{
			get
			{
				return this._ten_dang_nhap;
			}
			set
			{
				if ((this._ten_dang_nhap != value))
				{
					this.Onten_dang_nhapChanging(value);
					this.SendPropertyChanging();
					this._ten_dang_nhap = value;
					this.SendPropertyChanged("ten_dang_nhap");
					this.Onten_dang_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mat_khau", DbType="VarChar(20)")]
		public string mat_khau
		{
			get
			{
				return this._mat_khau;
			}
			set
			{
				if ((this._mat_khau != value))
				{
					this.Onmat_khauChanging(value);
					this.SendPropertyChanging();
					this._mat_khau = value;
					this.SendPropertyChanged("mat_khau");
					this.Onmat_khauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_hoa_don")]
	public partial class CT_hoa_don : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_CT_hoa_don;
		
		private System.Nullable<int> _ma_san_pham;
		
		private System.Nullable<int> _ma_hoa_don;
		
		private System.Nullable<int> _so_luong;
		
		private System.Nullable<decimal> _thanh_tien;
		
		private EntityRef<Hoa_don> _Hoa_don;
		
		private EntityRef<San_pham> _San_pham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_CT_hoa_donChanging(int value);
    partial void Onma_CT_hoa_donChanged();
    partial void Onma_san_phamChanging(System.Nullable<int> value);
    partial void Onma_san_phamChanged();
    partial void Onma_hoa_donChanging(System.Nullable<int> value);
    partial void Onma_hoa_donChanged();
    partial void Onso_luongChanging(System.Nullable<int> value);
    partial void Onso_luongChanged();
    partial void Onthanh_tienChanging(System.Nullable<decimal> value);
    partial void Onthanh_tienChanged();
    #endregion
		
		public CT_hoa_don()
		{
			this._Hoa_don = default(EntityRef<Hoa_don>);
			this._San_pham = default(EntityRef<San_pham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_CT_hoa_don", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_CT_hoa_don
		{
			get
			{
				return this._ma_CT_hoa_don;
			}
			set
			{
				if ((this._ma_CT_hoa_don != value))
				{
					this.Onma_CT_hoa_donChanging(value);
					this.SendPropertyChanging();
					this._ma_CT_hoa_don = value;
					this.SendPropertyChanged("ma_CT_hoa_don");
					this.Onma_CT_hoa_donChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_san_pham", DbType="Int")]
		public System.Nullable<int> ma_san_pham
		{
			get
			{
				return this._ma_san_pham;
			}
			set
			{
				if ((this._ma_san_pham != value))
				{
					if (this._San_pham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_san_phamChanging(value);
					this.SendPropertyChanging();
					this._ma_san_pham = value;
					this.SendPropertyChanged("ma_san_pham");
					this.Onma_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_hoa_don", DbType="Int")]
		public System.Nullable<int> ma_hoa_don
		{
			get
			{
				return this._ma_hoa_don;
			}
			set
			{
				if ((this._ma_hoa_don != value))
				{
					if (this._Hoa_don.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_hoa_donChanging(value);
					this.SendPropertyChanging();
					this._ma_hoa_don = value;
					this.SendPropertyChanged("ma_hoa_don");
					this.Onma_hoa_donChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int")]
		public System.Nullable<int> so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanh_tien", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> thanh_tien
		{
			get
			{
				return this._thanh_tien;
			}
			set
			{
				if ((this._thanh_tien != value))
				{
					this.Onthanh_tienChanging(value);
					this.SendPropertyChanging();
					this._thanh_tien = value;
					this.SendPropertyChanged("thanh_tien");
					this.Onthanh_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hoa_don_CT_hoa_don", Storage="_Hoa_don", ThisKey="ma_hoa_don", OtherKey="ma_hoa_don", IsForeignKey=true, DeleteRule="CASCADE")]
		public Hoa_don Hoa_don
		{
			get
			{
				return this._Hoa_don.Entity;
			}
			set
			{
				Hoa_don previousValue = this._Hoa_don.Entity;
				if (((previousValue != value) 
							|| (this._Hoa_don.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hoa_don.Entity = null;
						previousValue.CT_hoa_dons.Remove(this);
					}
					this._Hoa_don.Entity = value;
					if ((value != null))
					{
						value.CT_hoa_dons.Add(this);
						this._ma_hoa_don = value.ma_hoa_don;
					}
					else
					{
						this._ma_hoa_don = default(Nullable<int>);
					}
					this.SendPropertyChanged("Hoa_don");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="San_pham_CT_hoa_don", Storage="_San_pham", ThisKey="ma_san_pham", OtherKey="ma_san_pham", IsForeignKey=true, DeleteRule="CASCADE")]
		public San_pham San_pham
		{
			get
			{
				return this._San_pham.Entity;
			}
			set
			{
				San_pham previousValue = this._San_pham.Entity;
				if (((previousValue != value) 
							|| (this._San_pham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._San_pham.Entity = null;
						previousValue.CT_hoa_dons.Remove(this);
					}
					this._San_pham.Entity = value;
					if ((value != null))
					{
						value.CT_hoa_dons.Add(this);
						this._ma_san_pham = value.ma_san_pham;
					}
					else
					{
						this._ma_san_pham = default(Nullable<int>);
					}
					this.SendPropertyChanged("San_pham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khach_hang")]
	public partial class Khach_hang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_khach_hang;
		
		private string _email;
		
		private string _mat_khau;
		
		private string _ten_khach_hang;
		
		private string _so_dien_thoai;
		
		private string _dia_chi;
		
		private EntitySet<Hoa_don> _Hoa_dons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_khach_hangChanging(int value);
    partial void Onma_khach_hangChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onmat_khauChanging(string value);
    partial void Onmat_khauChanged();
    partial void Onten_khach_hangChanging(string value);
    partial void Onten_khach_hangChanged();
    partial void Onso_dien_thoaiChanging(string value);
    partial void Onso_dien_thoaiChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    #endregion
		
		public Khach_hang()
		{
			this._Hoa_dons = new EntitySet<Hoa_don>(new Action<Hoa_don>(this.attach_Hoa_dons), new Action<Hoa_don>(this.detach_Hoa_dons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_khach_hang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_khach_hang
		{
			get
			{
				return this._ma_khach_hang;
			}
			set
			{
				if ((this._ma_khach_hang != value))
				{
					this.Onma_khach_hangChanging(value);
					this.SendPropertyChanging();
					this._ma_khach_hang = value;
					this.SendPropertyChanged("ma_khach_hang");
					this.Onma_khach_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mat_khau", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string mat_khau
		{
			get
			{
				return this._mat_khau;
			}
			set
			{
				if ((this._mat_khau != value))
				{
					this.Onmat_khauChanging(value);
					this.SendPropertyChanging();
					this._mat_khau = value;
					this.SendPropertyChanged("mat_khau");
					this.Onmat_khauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_khach_hang", DbType="NVarChar(50)")]
		public string ten_khach_hang
		{
			get
			{
				return this._ten_khach_hang;
			}
			set
			{
				if ((this._ten_khach_hang != value))
				{
					this.Onten_khach_hangChanging(value);
					this.SendPropertyChanging();
					this._ten_khach_hang = value;
					this.SendPropertyChanged("ten_khach_hang");
					this.Onten_khach_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dien_thoai", DbType="VarChar(20)")]
		public string so_dien_thoai
		{
			get
			{
				return this._so_dien_thoai;
			}
			set
			{
				if ((this._so_dien_thoai != value))
				{
					this.Onso_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._so_dien_thoai = value;
					this.SendPropertyChanged("so_dien_thoai");
					this.Onso_dien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(100)")]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khach_hang_Hoa_don", Storage="_Hoa_dons", ThisKey="ma_khach_hang", OtherKey="ma_khach_hang")]
		public EntitySet<Hoa_don> Hoa_dons
		{
			get
			{
				return this._Hoa_dons;
			}
			set
			{
				this._Hoa_dons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hoa_dons(Hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.Khach_hang = this;
		}
		
		private void detach_Hoa_dons(Hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.Khach_hang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hoa_don")]
	public partial class Hoa_don : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_hoa_don;
		
		private System.Nullable<System.DateTime> _ngay_dat_hang;
		
		private System.Nullable<int> _ma_khach_hang;
		
		private System.Nullable<decimal> _tong;
		
		private string _trang_thai;
		
		private string _ghi_chu;
		
		private System.Nullable<decimal> _phi_van_chuyen;
		
		private EntitySet<CT_hoa_don> _CT_hoa_dons;
		
		private EntityRef<Khach_hang> _Khach_hang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_hoa_donChanging(int value);
    partial void Onma_hoa_donChanged();
    partial void Onngay_dat_hangChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_dat_hangChanged();
    partial void Onma_khach_hangChanging(System.Nullable<int> value);
    partial void Onma_khach_hangChanged();
    partial void OntongChanging(System.Nullable<decimal> value);
    partial void OntongChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Onphi_van_chuyenChanging(System.Nullable<decimal> value);
    partial void Onphi_van_chuyenChanged();
    #endregion
		
		public Hoa_don()
		{
			this._CT_hoa_dons = new EntitySet<CT_hoa_don>(new Action<CT_hoa_don>(this.attach_CT_hoa_dons), new Action<CT_hoa_don>(this.detach_CT_hoa_dons));
			this._Khach_hang = default(EntityRef<Khach_hang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_hoa_don", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_hoa_don
		{
			get
			{
				return this._ma_hoa_don;
			}
			set
			{
				if ((this._ma_hoa_don != value))
				{
					this.Onma_hoa_donChanging(value);
					this.SendPropertyChanging();
					this._ma_hoa_don = value;
					this.SendPropertyChanged("ma_hoa_don");
					this.Onma_hoa_donChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_dat_hang", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_dat_hang
		{
			get
			{
				return this._ngay_dat_hang;
			}
			set
			{
				if ((this._ngay_dat_hang != value))
				{
					this.Onngay_dat_hangChanging(value);
					this.SendPropertyChanging();
					this._ngay_dat_hang = value;
					this.SendPropertyChanged("ngay_dat_hang");
					this.Onngay_dat_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_khach_hang", DbType="Int")]
		public System.Nullable<int> ma_khach_hang
		{
			get
			{
				return this._ma_khach_hang;
			}
			set
			{
				if ((this._ma_khach_hang != value))
				{
					if (this._Khach_hang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_khach_hangChanging(value);
					this.SendPropertyChanging();
					this._ma_khach_hang = value;
					this.SendPropertyChanged("ma_khach_hang");
					this.Onma_khach_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> tong
		{
			get
			{
				return this._tong;
			}
			set
			{
				if ((this._tong != value))
				{
					this.OntongChanging(value);
					this.SendPropertyChanging();
					this._tong = value;
					this.SendPropertyChanged("tong");
					this.OntongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="VarChar(20)")]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(100)")]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phi_van_chuyen", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> phi_van_chuyen
		{
			get
			{
				return this._phi_van_chuyen;
			}
			set
			{
				if ((this._phi_van_chuyen != value))
				{
					this.Onphi_van_chuyenChanging(value);
					this.SendPropertyChanging();
					this._phi_van_chuyen = value;
					this.SendPropertyChanged("phi_van_chuyen");
					this.Onphi_van_chuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hoa_don_CT_hoa_don", Storage="_CT_hoa_dons", ThisKey="ma_hoa_don", OtherKey="ma_hoa_don")]
		public EntitySet<CT_hoa_don> CT_hoa_dons
		{
			get
			{
				return this._CT_hoa_dons;
			}
			set
			{
				this._CT_hoa_dons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khach_hang_Hoa_don", Storage="_Khach_hang", ThisKey="ma_khach_hang", OtherKey="ma_khach_hang", IsForeignKey=true, DeleteRule="CASCADE")]
		public Khach_hang Khach_hang
		{
			get
			{
				return this._Khach_hang.Entity;
			}
			set
			{
				Khach_hang previousValue = this._Khach_hang.Entity;
				if (((previousValue != value) 
							|| (this._Khach_hang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khach_hang.Entity = null;
						previousValue.Hoa_dons.Remove(this);
					}
					this._Khach_hang.Entity = value;
					if ((value != null))
					{
						value.Hoa_dons.Add(this);
						this._ma_khach_hang = value.ma_khach_hang;
					}
					else
					{
						this._ma_khach_hang = default(Nullable<int>);
					}
					this.SendPropertyChanged("Khach_hang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_hoa_dons(CT_hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.Hoa_don = this;
		}
		
		private void detach_CT_hoa_dons(CT_hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.Hoa_don = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Loai_nong_san")]
	public partial class Loai_nong_san : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_nong_san;
		
		private string _ten_loai;
		
		private EntitySet<San_pham> _San_phams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_nong_sanChanging(int value);
    partial void Onma_nong_sanChanged();
    partial void Onten_loaiChanging(string value);
    partial void Onten_loaiChanged();
    #endregion
		
		public Loai_nong_san()
		{
			this._San_phams = new EntitySet<San_pham>(new Action<San_pham>(this.attach_San_phams), new Action<San_pham>(this.detach_San_phams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_nong_san", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_nong_san
		{
			get
			{
				return this._ma_nong_san;
			}
			set
			{
				if ((this._ma_nong_san != value))
				{
					this.Onma_nong_sanChanging(value);
					this.SendPropertyChanging();
					this._ma_nong_san = value;
					this.SendPropertyChanged("ma_nong_san");
					this.Onma_nong_sanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_loai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_loai
		{
			get
			{
				return this._ten_loai;
			}
			set
			{
				if ((this._ten_loai != value))
				{
					this.Onten_loaiChanging(value);
					this.SendPropertyChanging();
					this._ten_loai = value;
					this.SendPropertyChanged("ten_loai");
					this.Onten_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loai_nong_san_San_pham", Storage="_San_phams", ThisKey="ma_nong_san", OtherKey="ma_nong_san")]
		public EntitySet<San_pham> San_phams
		{
			get
			{
				return this._San_phams;
			}
			set
			{
				this._San_phams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_San_phams(San_pham entity)
		{
			this.SendPropertyChanging();
			entity.Loai_nong_san = this;
		}
		
		private void detach_San_phams(San_pham entity)
		{
			this.SendPropertyChanging();
			entity.Loai_nong_san = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.San_pham")]
	public partial class San_pham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ma_san_pham;
		
		private string _ten_san_pham;
		
		private string _hinh_anh;
		
		private int _ma_nong_san;
		
		private System.Nullable<decimal> _gia;
		
		private string _don_vi_tinh;
		
		private System.Nullable<int> _so_luong;
		
		private System.Nullable<System.DateTime> _ngay_them;
		
		private EntitySet<CT_hoa_don> _CT_hoa_dons;
		
		private EntityRef<Loai_nong_san> _Loai_nong_san;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_san_phamChanging(int value);
    partial void Onma_san_phamChanged();
    partial void Onten_san_phamChanging(string value);
    partial void Onten_san_phamChanged();
    partial void Onhinh_anhChanging(string value);
    partial void Onhinh_anhChanged();
    partial void Onma_nong_sanChanging(int value);
    partial void Onma_nong_sanChanged();
    partial void OngiaChanging(System.Nullable<decimal> value);
    partial void OngiaChanged();
    partial void Ondon_vi_tinhChanging(string value);
    partial void Ondon_vi_tinhChanged();
    partial void Onso_luongChanging(System.Nullable<int> value);
    partial void Onso_luongChanged();
    partial void Onngay_themChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_themChanged();
    #endregion
		
		public San_pham()
		{
			this._CT_hoa_dons = new EntitySet<CT_hoa_don>(new Action<CT_hoa_don>(this.attach_CT_hoa_dons), new Action<CT_hoa_don>(this.detach_CT_hoa_dons));
			this._Loai_nong_san = default(EntityRef<Loai_nong_san>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_san_pham", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ma_san_pham
		{
			get
			{
				return this._ma_san_pham;
			}
			set
			{
				if ((this._ma_san_pham != value))
				{
					this.Onma_san_phamChanging(value);
					this.SendPropertyChanging();
					this._ma_san_pham = value;
					this.SendPropertyChanged("ma_san_pham");
					this.Onma_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_san_pham", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_san_pham
		{
			get
			{
				return this._ten_san_pham;
			}
			set
			{
				if ((this._ten_san_pham != value))
				{
					this.Onten_san_phamChanging(value);
					this.SendPropertyChanging();
					this._ten_san_pham = value;
					this.SendPropertyChanged("ten_san_pham");
					this.Onten_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_anh", DbType="VarChar(100)")]
		public string hinh_anh
		{
			get
			{
				return this._hinh_anh;
			}
			set
			{
				if ((this._hinh_anh != value))
				{
					this.Onhinh_anhChanging(value);
					this.SendPropertyChanging();
					this._hinh_anh = value;
					this.SendPropertyChanged("hinh_anh");
					this.Onhinh_anhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_nong_san", DbType="Int NOT NULL")]
		public int ma_nong_san
		{
			get
			{
				return this._ma_nong_san;
			}
			set
			{
				if ((this._ma_nong_san != value))
				{
					if (this._Loai_nong_san.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_nong_sanChanging(value);
					this.SendPropertyChanging();
					this._ma_nong_san = value;
					this.SendPropertyChanged("ma_nong_san");
					this.Onma_nong_sanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_don_vi_tinh", DbType="NVarChar(50)")]
		public string don_vi_tinh
		{
			get
			{
				return this._don_vi_tinh;
			}
			set
			{
				if ((this._don_vi_tinh != value))
				{
					this.Ondon_vi_tinhChanging(value);
					this.SendPropertyChanging();
					this._don_vi_tinh = value;
					this.SendPropertyChanged("don_vi_tinh");
					this.Ondon_vi_tinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int")]
		public System.Nullable<int> so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_them", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_them
		{
			get
			{
				return this._ngay_them;
			}
			set
			{
				if ((this._ngay_them != value))
				{
					this.Onngay_themChanging(value);
					this.SendPropertyChanging();
					this._ngay_them = value;
					this.SendPropertyChanged("ngay_them");
					this.Onngay_themChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="San_pham_CT_hoa_don", Storage="_CT_hoa_dons", ThisKey="ma_san_pham", OtherKey="ma_san_pham")]
		public EntitySet<CT_hoa_don> CT_hoa_dons
		{
			get
			{
				return this._CT_hoa_dons;
			}
			set
			{
				this._CT_hoa_dons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loai_nong_san_San_pham", Storage="_Loai_nong_san", ThisKey="ma_nong_san", OtherKey="ma_nong_san", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Loai_nong_san Loai_nong_san
		{
			get
			{
				return this._Loai_nong_san.Entity;
			}
			set
			{
				Loai_nong_san previousValue = this._Loai_nong_san.Entity;
				if (((previousValue != value) 
							|| (this._Loai_nong_san.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Loai_nong_san.Entity = null;
						previousValue.San_phams.Remove(this);
					}
					this._Loai_nong_san.Entity = value;
					if ((value != null))
					{
						value.San_phams.Add(this);
						this._ma_nong_san = value.ma_nong_san;
					}
					else
					{
						this._ma_nong_san = default(int);
					}
					this.SendPropertyChanged("Loai_nong_san");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_hoa_dons(CT_hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.San_pham = this;
		}
		
		private void detach_CT_hoa_dons(CT_hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.San_pham = null;
		}
	}
}
#pragma warning restore 1591
